name: TopoDockQ

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.18
  - numpy<=1.24.3
  - pandas<=2.2.0
  - scikit-learn=1.3.0
  - gudhi=3.8.0
  - pip
  - pip:
    - torch>=2.0.0
    - torchvision
    - matplotlib>=3.5.0
    - scipy>=1.9.0
    - pillow>=8.0.0
