name: prody
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - scipy=1.10.1
  - matplotlib=3.7.1
  - prody=2.4.1
  - pip
  - pip:
    # ProDy is available via conda-forge, but adding pip as backup
    # No additional pip packages needed for basic ProDy functionality

